name: protein_scoring
channels:
  - defaults
  - bioconda
  - conda-forge
  - ostrokach-forge
  - esri
dependencies:
  - python=3.8
  - pandas~=1.3.5
  - biopython~=1.79
  # - jupyterlab~=3.3.4
  - seaborn~=0.11.2
  - pip
  - scipy~=1.7.3
  - scikit-learn~=1.2.1
  - ete3~=3.1.2
  - pyqt~=5.9.2
  - fasta3~=36.3.8
  - torch-scatter
  - torch-sparse
  - torch-cluster
  - torch-spline-conv
  - pytorch_geometric
  - pip:
      - biotite
      - pytest-datadir
      - sequence-models
      - biopython~=1.79
      - pytest-datadir~=1.4.1
      - "git+https://github.com/facebookresearch/esm.git@e5e7b06b9a093706607c229ab1c5c9821806814d" # ESM